import Head from 'next/head'

export default function Header(){
    return(
        <Head>
            <title>Home Finder</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/houseIcon.png" />
        </Head>
    )
}